#!/bin/bash

{
echo //
echo // This file is autogenerated from dsl.cpp, do not change.
echo //
echo
echo 'std::unordered_map<std::string, data_type> string2enum = {'
perl -lne 'print "\t{\"" . lc($1). "\", $1}," if /^\s+([_A-Z]+),$/' < dsl.cpp
echo '};'
echo
} > dsl_tables.h
